# Generated by Django 3.0.8 on 2020-09-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_watchlist_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Cars and Vehicles', 'Cars and Vehicles'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Tools', 'Tools'), ('Books', 'Books'), ('Toys', 'Toys'), ('Pet', 'Pet'), ('Service', 'Service'), ('Other', 'Other')], max_length=64),
        ),
    ]
