# Generated by Django 3.0.8 on 2020-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='max_bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.URLField(default=True),
        ),
    ]
