# Generated by Django 3.0.8 on 2020-09-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200904_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
